# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingHistory',
            fields=[
                ('bookingHistoryID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bookingRecord',
            fields=[
                ('bookingRecordID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('facilityID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('facilityName', models.CharField(max_length=50)),
                ('facilityDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='periods',
            fields=[
                ('periodID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('periodName', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='roomAvailability',
            fields=[
                ('roomAvailabilityID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('periodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods')),
            ],
        ),
        migrations.CreateModel(
            name='roomFacilities',
            fields=[
                ('roomFacilitiesID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('facilityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.facilities')),
            ],
        ),
        migrations.CreateModel(
            name='roomInfo',
            fields=[
                ('roomID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=50)),
                ('roomDescription', models.CharField(max_length=200)),
                ('roomCapacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='roomfacilities',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomInfo'),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='periodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods'),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomInfo'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='periodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomInfo'),
        ),
    ]
