# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bookingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('facilityID', models.AutoField(primary_key=True, serialize=False)),
                ('facilityName', models.CharField(max_length=50)),
                ('facilityDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='periods',
            fields=[
                ('periodID', models.AutoField(primary_key=True, serialize=False)),
                ('periodName', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='roomAvaliability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('periodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods')),
            ],
        ),
        migrations.CreateModel(
            name='roomInfo',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=50)),
                ('roomDescription', models.CharField(max_length=200)),
                ('roomCapacity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.CreateModel(
            name='roomFacilities',
            fields=[
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.roomInfo')),
                ('facilityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.facilities')),
            ],
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='periodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='periodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.periods'),
        ),
    ]
