# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('roomFacilitiesID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='facilities',
            new_name='Facility',
        ),
        migrations.RenameModel(
            old_name='periods',
            new_name='Period',
        ),
        migrations.RenameModel(
            old_name='roomInfo',
            new_name='Room',
        ),
        migrations.RemoveField(
            model_name='bookingrecord',
            name='periodID',
        ),
        migrations.RemoveField(
            model_name='bookingrecord',
            name='roomID',
        ),
        migrations.RemoveField(
            model_name='roomavailability',
            name='periodID',
        ),
        migrations.RemoveField(
            model_name='roomfacilities',
            name='facilityID',
        ),
        migrations.RemoveField(
            model_name='roomfacilities',
            name='roomID',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='periodID',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='roomID',
        ),
        migrations.DeleteModel(
            name='bookingRecord',
        ),
        migrations.DeleteModel(
            name='roomAvailability',
        ),
        migrations.DeleteModel(
            name='roomFacilities',
        ),
        migrations.AddField(
            model_name='roomfacility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Facility'),
        ),
        migrations.AddField(
            model_name='roomfacility',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Period'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
