# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180204_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='periodName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='roomName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
