# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180311_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facilities', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='roomfacility',
            options={'verbose_name': 'Room Facilities', 'verbose_name_plural': 'Room Facilities'},
        ),
    ]
