# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20180311_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
